name: DB Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: build db docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set current date as TAG env variable for push requests
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t hakaiinstitute/postgresql:$TAG -t hakaiinstitute/postgresql:latest --file ./contrib/docker/postgresql/Dockerfile .
    - run: docker push hakaiinstitute/postgresql:$TAG
    - run: docker push hakaiinstitute/postgresql:latest
